export default [
  {
    trigramme: "BRM",
    nom: "Martins",
    prenom: "Bandone",
    surnom: "Brondon",
    photo: "",
    tribu: "WEBF",
    signeParticulier: "rit très fort",
    dateNaissance: new Date(1993, 8, 14),
  },
  {
    trigramme: "MBI",
    nom: "Biardeau",
    prenom: "Marie",
    surnom: "Marizouz",
    photo: "",
    tribu: "OCAC",
    signeParticulier: "boit des shots",
    dateNaissance: new Date(),
  },
  {
    trigramme: "RDO",
    nom: "Dormoy",
    prenom: "Remi",
    surnom: "Rémido",
    photo: "",
    tribu: "MOB",
    signeParticulier: "boit du Ricard",
    dateNaissance: new Date(),
  },
  {
    trigramme: "BEJ",
    nom: "Jarlier",
    prenom: "Benoit",
    surnom: "Bénoit",
    photo: "",
    tribu: "NAD",
    signeParticulier: "boit beaucoup",
    dateNaissance: new Date(),
  },
  {
    trigramme: "LAAL",
    nom: "Lambert",
    prenom: "Alizée",
    surnom: "Alizouz",
    photo: "",
    tribu: "UX",
    signeParticulier: "voit le bon côté des choses",
    dateNaissance: new Date(),
  },
  {
    trigramme: "DAS",
    nom: "Sala",
    prenom: "Daniel",
    surnom: "Daniboy",
    photo: "",
    tribu: "",
    signeParticulier: "danse exceptionnellement bien",
    dateNaissance: new Date(),
  },
  {
    trigramme: "JDO",
    nom: "Dompe",
    prenom: "Juliette",
    surnom: "Juju",
    photo: "",
    tribu: "ARCHI",
    signeParticulier: "fait des cocktails",
    dateNaissance: new Date(),
  },
  {
    trigramme: "BME",
    nom: "Meriaux",
    prenom: "Benoit",
    surnom: "Renoit",
    photo: "",
    tribu: "NAD",
    signeParticulier: "court très vite",
    dateNaissance: new Date(),
  },
  {
    trigramme: "FAM",
    nom: "Massin",
    prenom: "Faustine",
    surnom: "Faustino",
    photo: "",
    tribu: "NAD",
    signeParticulier: "parle beaucoup de sexe",
    dateNaissance: new Date(),
  },
  {
    trigramme: "CLI",
    nom: "Liu",
    prenom: "Can",
    surnom: "Can",
    photo: "",
    tribu: "ARCHI",
    signeParticulier: "sait bien faire vibrer ses fesses",
    dateNaissance: new Date(),
  },
  {
    trigramme: "CEM",
    nom: "Martin",
    prenom: "Cedric",
    surnom: "Cédric",
    photo: "",
    tribu: "NAD",
    signeParticulier: "maîtrise l'art de maîtriser",
    dateNaissance: new Date(),
  },
  {
    trigramme: "CYG",
    nom: "Guegan",
    prenom: "Cyril",
    surnom: "Cygounette",
    photo: "",
    tribu: "ARCHI",
    signeParticulier: "Met des grandes claques dans le dos",
    dateNaissance: new Date(),
  },
  {
    trigramme: "MEG",
    nom: "Menanteau",
    prenom: "Mégane",
    surnom: "Meg",
    photo: "",
    tribu: "WEBF",
    signeParticulier: "te regarde mal",
    dateNaissance: new Date(),
  },
  {
    trigramme: "JORO",
    nom: "Robert",
    prenom: "Joseph",
    surnom: "JOROOOOO",
    photo: "",
    tribu: "ARCHI",
    signeParticulier: "Court très vite",
    dateNaissance: new Date(),
  },
  {
    trigramme: "LJA",
    nom: "Jacquemin",
    prenom: "Leo",
    surnom: "Léo",
    photo: "",

    tribu: "WEBF",
    signeParticulier: "fait des dry january indéfiniment",
    dateNaissance: new Date(),
  },
  {
    trigramme: "MID",
    nom: "Durdevic",
    prenom: "Mila",
    surnom: "Mila",
    photo: "",
    tribu: "CRAFT",
    signeParticulier: "Prend une grande caisse par an",
    dateNaissance: new Date(),
  },
  {
    trigramme: "SLU",
    nom: "Lundy",
    prenom: "Stéphane",
    surnom: "Le Mondai",
    photo: "",
    tribu: "Autres",
    signeParticulier: "Maîtrise le feu",
    dateNaissance: new Date(),
  },
  {
    trigramme: "RBO",
    nom: "Botter",
    prenom: "Rafaëlle",
    surnom: "La Botter",
    photo: "",
    tribu: "Autres",
    signeParticulier: "",
    dateNaissance: new Date(),
  },
]