# stage: 1
FROM node:12.2.0-alpine

WORKDIR /doggy-app

# install and cache app dependencies
COPY package.json /doggy-app/package.json
RUN yarn install --silent
RUN yarn add react-scripts@3.0.1 -g --silent
COPY . .

# start app
CMD ["yarn", "start"]